### ISSUE TITLE
Unable to load

### ISSUE THREAD

**Issue by HeavyTony2** [hnmr293/stable-diffusion-webui-dumpunet#1]
`Error loading script: dumpunet.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-dumpunet/scripts/dumpunet.py", line 10, in <module>
    from scripts.lib.build_ui import UI
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-dumpunet/scripts/lib/build_ui.py", line 9, in <module>
    from scripts.lib import layerinfo
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-dumpunet/scripts/lib/layerinfo.py", line 5, in <module>
    Names_IN : tuple[str, ...] = (
TypeError: 'type' object is not subscriptable`

**Comment by hnmr293** [comment]
sorry, this extension needs python3.10.

**Comment by HeavyTony2** [comment]
> sorry, this extension needs python3.10.

Oh, I see, thanks.
