### ISSUE TITLE
使用layer prompt的时候显示的两张图一样，其实生成的是两张不同的图，但是都显示了同一张

### ISSUE THREAD

**Issue by iconnoci** [hnmr293/stable-diffusion-webui-dumpunet#3]
使用layer prompt的时候显示的两张图一样，其实生成的是两张不同的图，但是都显示了同一张
正确生成了两张图
![QQ截图20230327152254](https://user-images.githubusercontent.com/22522962/227869445-22843c6e-b891-4319-8706-7d70c166360c.png)
显示都是同一张，好几次都以为自己用错了，后来翻看存档才知道显示错误
![QQ截图20230327152022](https://user-images.githubusercontent.com/22522962/227869103-396a24ac-f634-4e1d-ae10-16580b7995b1.png)
![QQ截图20230327152204](https://user-images.githubusercontent.com/22522962/227869241-890226e9-45e6-40e1-ae99-5a8eeef754b8.png)
 另外想问一下 unet features和attention layers' features 这两个可以用具体讲解用法吗？出来的差异图看不懂啊。

**Comment by hnmr293** [comment]
I have read your comment with machine translation. Sorry if my understanding is wrong.

Layer prompt is the feature that gives separate prompts for each layer of U-Net.
If prompts are same, the same image will be generated. And if the given layer cannot recognize the difference in prompts, it will still produce (almost) the same image.

Here is English version of README.md
https://github.com/hnmr293/stable-diffusion-webui-dumpunet/blob/master/README_en.md

Please let me know the prompts you used.

**Comment by iconnoci** [comment]
有看到你4月1日，做了更新，所以想继续测试一下，
也不知道最近我更新了哪些东西导致layer prompt导致无法使用了。。。。。，前两个功能是正常的
I saw that you made an update on April 1, so I want to continue testing,
I don't know what things I updated recently that caused the layer prompt to be unusable. . . . . , the first two functions are normal

ps:看着像是到了composable-lora。。。。。。


error:
 Error completing request
Arguments: ('task(n93adt50as45dc8)', 'a (~: IN00-OUT11: cute ; M00: excellent :~) girl', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 12, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, False, True, True, 0, 960, 64, False, '', 0, 3, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', 1, False, 7, 100, 'Constant', 0, 'Constant', 0, 4, <scripts.external_code.ControlNetUnit object at 0x0000024D4C4F6200>, <scripts.external_code.ControlNetUnit object at 0x0000024D4C4F6230>, False, 1, 0.15, False, 'OUT', ['OUT'], 5, 0, 'Bilinear', False, 'Pooling Max', False, 'Lerp', '', '', False, 'INALLMIDD:1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0\nOUTALLMIDD:1,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1\nyifu:1,0,0,0,0,0.75,0.25,1,1,0,0,0,0,0,0,0,0\nXYZ:1,0,0,0,0,0.75,0.25,1,0.5,0.75,0.75,0,0,0,0,0,0\nNOT:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUTS:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nbodyh:1,1,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1\nbodys:1,1,1,1,1,1,0.2,1,0.2,0,0,0.8,1,1,1,1,1\nfaceh:1,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0\nfaces:1,0,0,0,0,0,0,0,0.8,1,1,0.2,0,0,0,0,0\nclothe:1,1,1,1,1,0,0.2,0,0.8,1,1,0.2,0,0,0,0,0\nact:1,0,0,0,0,0,0.2,1,1,1,0,0,0,0,0,0,0\ncolor:1,0,0,0,0,0,0,0,0,0,0,0.8,1,1,1,1,1\nchar:1,1,1,1,1,0,0,0,1,1,1,1,1,1,1,0,0\nbackground:1,1,1,1,1,1,0.2,1,0.2,0,0,0.8,1,1,1,0,0\nlowover:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1', True, 0, 'values', '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1', 'BASE,IN01,IN02,IN04,IN05,IN07,IN08,M00,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 'black', '20', False, False, False, 'Horizontal', '1,1', '0.2', False, False, False, 'Attention', False, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, False, False, 3, 0, False, False, 0, False, False, False, False, '', 1, '', 0, '', True, False, False, False, False, None, None, '', '', '', '', 'Auto rename', {'label': 'Upload avatars config'}, 'Open outputs directory', 'Export to WebUI style', True, {'label': 'Presets'}, {'label': 'QC preview'}, '', [], 'Select', 'QC scan', 'Show pics', None, False, False, 'positive', 'comma', 0, False, False, '', False, '', False, [], [], [], [], [], [], [], [], [], 0, 'Median cut', 'luminance', False, 1, '', 0, '', 0, '', True, False, False, False, 0, False, False, False, '#000000', None, False, None, False, 50, False, 'IN00-OUT11', '20', 'disable', 'Custom', 'HSL', 'abs(v)', 'abs(v)', 'abs(v)', '(2+v)/3', '1.0', '0.5', 'Auto [0,1]', -1, 1, 1, 0, False, '', False, 'IN00-OUT11', '20', 'disable', ['K'], 'Custom', 'HSL', 'abs(v)', 'abs(v)', 'abs(v)', '(2+v)/3', '1.0', '0.5', 'Auto [0,1]', -1, 1, 1, 0, False, '', True, True, 'IN00-OUT11', '20', 'disable', 'Custom', 'HSL', 'abs(v)', 'abs(v)', 'abs(v)', '(2+v)/3', '1.0', '0.5', 'Auto [0,1]', -1, 1, 1, 0, False, '', False) {}
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui\modules\txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "D:\stable-diffusion-webui\modules\scripts.py", line 399, in run
    processed = script.run(p, *script_args)
  File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-dumpunet\scripts\dumpunet.py", line 112, in run
    return self.run_impl(p, *args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-dumpunet\scripts\dumpunet.py", line 215, in run_impl    proc1, features1, diff1, attn1 = exec(p1, lp0, [ex, exlp, at])
  File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-dumpunet\scripts\dumpunet.py", line 279, in exec
    proc = process_images(p)
  File "D:\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "D:\stable-diffusion-webui\modules\processing.py", line 636, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "D:\stable-diffusion-webui\modules\processing.py", line 836, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "D:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 351, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "D:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 227, in launch_sampling
    return func()
  File "D:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 351, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 119, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "D:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "D:\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "D:\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "D:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-dumpunet\scripts\dumpunetlib\layer_prompt\prompt.py", line 180, in new_forward
    h = module(h, emb, layer_conds[cond_index] if context is not None else None)    # context)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 86, in forward
    x = layer(x)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-composable-lora\composable_lora.py", line 154, in lora_Conv2d_forward
    return lora_forward(self, input, torch.nn.Conv2d_forward_before_lora(self, input))
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.HalfTensor) should be the same

**Comment by iconnoci** [comment]
The two pictures are the same, shouldn't they be different? , there are two different pictures in the output folder directory
Sorry, it’s still me, still the same problem, I updated your update on April 1, thinking it solved the problem, but the problem is still there, two different pictures are generated but the same picture is displayed on the webui。


两张图片是相同，不应该是不一样的吗？，在output文件夹目录里是两张不一样的图片
对不住，还是我 ，还是同一样的问题，我更新了你4月1日的更新，以为解决了问题，但是问题还在，生成了两张不同的图片但是webui上显示的还是同一张图片
![Snipaste_2023-04-09_09-32-55](https://user-images.githubusercontent.com/22522962/230749864-b8dbacc9-b3da-4a92-934b-a9f7d065f180.png)

**Comment by hnmr293** [comment]
Oh, sorry! It is my mistake.
I've fixed the issue. Please try it again!

![image](https://user-images.githubusercontent.com/120772120/230903475-3a39ae9c-349e-4258-862c-e69712c614b0.png)

**Comment by iconnoci** [comment]
successful repair
