### ISSUE TITLE
Just crash or return unusable picture (a1111 v1.8, sd1.5)

### ISSUE THREAD

**Issue by ghost** [hnmr293/stable-diffusion-webui-dumpunet#6]
[DumpUnet] U-Net: hooking M00...
  0%|                                                                                           | 0/20 [00:00<?, ?it/s][DumpUnet] 1 M00 torch.Size([2, 1280, 12, 8]) torch.Size([2, 1280, 12, 8])
  5%|████▏                                                                              | 1/20 [00:00<00:18,  1.04it/s][DumpUnet] 2 M00 torch.Size([2, 1280, 12, 8]) torch.Size([2, 1280, 12, 8])
 10%|████████▎                                                                          | 2/20 [00:01<00:15,  1.14it/s][DumpUnet] 3 M00 torch.Size([2, 1280, 12, 8]) torch.Size([2, 1280, 12, 8])
 15%|████████████▍                                                                      | 3/20 [00:02<00:14,  1.19it/s][DumpUnet] 4 M00 torch.Size([2, 1280, 12, 8]) torch.Size([2, 1280, 12, 8])
 20%|████████████████▌                                                                  | 4/20 [00:03<00:13,  1.22it/s][DumpUnet] 5 M00 torch.Size([2, 1280, 12, 8]) torch.Size([2, 1280, 12, 8])
 25%|████████████████████▊                                                              | 5/20 [00:04<00:12,  1.23it/s][DumpUnet] 6 M00 torch.Size([2, 1280, 12, 8]) torch.Size([2, 1280, 12, 8])
 30%|████████████████████████▉                                                          | 6/20 [00:04<00:11,  1.23it/s][DumpUnet] 7 M00 torch.Size([2, 1280, 12, 8]) torch.Size([2, 1280, 12, 8])
 35%|█████████████████████████████                                                      | 7/20 [00:05<00:10,  1.23it/s][DumpUnet] 8 M00 torch.Size([2, 1280, 12, 8]) torch.Size([2, 1280, 12, 8])
 40%|█████████████████████████████████▏                                                 | 8/20 [00:06<00:09,  1.24it/s][DumpUnet] 9 M00 torch.Size([2, 1280, 12, 8]) torch.Size([2, 1280, 12, 8])
 45%|█████████████████████████████████████▎                                             | 9/20 [00:07<00:08,  1.25it/s][DumpUnet] 10 M00 torch.Size([2, 1280, 12, 8]) torch.Size([2, 1280, 12, 8])
 50%|█████████████████████████████████████████                                         | 10/20 [00:08<00:08,  1.25it/s][DumpUnet] 11 M00 torch.Size([2, 1280, 12, 8]) torch.Size([2, 1280, 12, 8])
 55%|█████████████████████████████████████████████                                     | 11/20 [00:08<00:07,  1.25it/s][DumpUnet] 12 M00 torch.Size([2, 1280, 12, 8]) torch.Size([2, 1280, 12, 8])
 60%|█████████████████████████████████████████████████▏                                | 12/20 [00:09<00:06,  1.25it/s][DumpUnet] 13 M00 torch.Size([2, 1280, 12, 8]) torch.Size([2, 1280, 12, 8])
 65%|█████████████████████████████████████████████████████▎                            | 13/20 [00:10<00:05,  1.25it/s][DumpUnet] 14 M00 torch.Size([2, 1280, 12, 8]) torch.Size([2, 1280, 12, 8])
 70%|█████████████████████████████████████████████████████████▍                        | 14/20 [00:11<00:04,  1.25it/s][DumpUnet] 15 M00 torch.Size([2, 1280, 12, 8]) torch.Size([2, 1280, 12, 8])
 75%|█████████████████████████████████████████████████████████████▌                    | 15/20 [00:12<00:03,  1.25it/s][DumpUnet] 16 M00 torch.Size([2, 1280, 12, 8]) torch.Size([2, 1280, 12, 8])
 80%|█████████████████████████████████████████████████████████████████▌                | 16/20 [00:12<00:03,  1.25it/s][DumpUnet] 17 M00 torch.Size([2, 1280, 12, 8]) torch.Size([2, 1280, 12, 8])
 85%|█████████████████████████████████████████████████████████████████████▋            | 17/20 [00:13<00:02,  1.25it/s][DumpUnet] 18 M00 torch.Size([2, 1280, 12, 8]) torch.Size([2, 1280, 12, 8])
 90%|█████████████████████████████████████████████████████████████████████████▊        | 18/20 [00:14<00:01,  1.23it/s][DumpUnet] 19 M00 torch.Size([2, 1280, 12, 8]) torch.Size([2, 1280, 12, 8])
 95%|█████████████████████████████████████████████████████████████████████████████▉    | 19/20 [00:15<00:00,  1.23it/s][DumpUnet] 20 M00 torch.Size([2, 1280, 12, 8]) torch.Size([2, 1280, 12, 8])
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:16<00:00,  1.23it/s]
*** Error completing request
*** Arguments: ('task(tx0re419mz2a84e)', <gradio.routes.Request object at 0x000001C970B885B0>, 'a cute girl\n', '(low quality, worst quality:1.4)', [], 20, 'Euler a', 1, 1, 7, 768, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], 5, False, '', 0.8, 2899652489, False, -1, 0, 0, 0, False, False, {'ad_model': 'face_yolov8n.pt', 'ad_model_classes': '', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 1, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 32, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'Euler a', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 32, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'Euler a', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'Euler a', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=512, threshold_a=64, threshold_b=64, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=512, threshold_a=64, threshold_b=64, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=512, threshold_a=64, threshold_b=64, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0, '', False, '', False, False, False, False, 'Auto', 0.5, 1, False, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50, True, 'M00', '', 'disable', 'Custom', 'HSL', 'abs(v)', 'abs(v)', 'abs(v)', '(2+v)/3', '1.0', '0.5', 'Auto [0,1]', -1, 1, 1, 0, False, '', False, 'M00', '1-20(+5)', 'sum', ['K'], 'Custom', 'HSL', 'abs(v)', 'abs(v)', 'abs(v)', '(2+v)/3', '1.0', '0.5', 'Auto [0,1]', -1, 1, 1, 0, False, '', False, True, 'M00', '1-20(+5)', 'sum', 'Custom', 'HSL', 'abs(v)', 'abs(v)', 'abs(v)', '(2+v)/3', '1.0', '0.5', 'Auto [0,1]', -1, 1, 1, 0, False, '', True, '', True) {}
    Traceback (most recent call last):
      File "F:\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "F:\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "F:\stable-diffusion-webui\modules\txt2img.py", line 107, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *p.script_args)
      File "F:\stable-diffusion-webui\modules\scripts.py", line 766, in run
        processed = script.run(p, *script_args)
      File "F:\stable-diffusion-webui\extensions\stable-diffusion-webui-dumpunet\scripts\dumpunet.py", line 114, in run
        return self.run_impl(p, *args, **kwargs)
      File "F:\stable-diffusion-webui\extensions\stable-diffusion-webui-dumpunet\scripts\dumpunet.py", line 268, in run_impl
        ex.add_images(p, builder, features1, favg, color)
      File "F:\stable-diffusion-webui\extensions\stable-diffusion-webui-dumpunet\scripts\dumpunetlib\features\extractor.py", line 82, in add_images
        super().add_images(*args, **kwargs)
      File "F:\stable-diffusion-webui\extensions\stable-diffusion-webui-dumpunet\scripts\dumpunetlib\feature_extractor.py", line 135, in add_images
        shared.total_tqdm._tqdm.set_postfix_str(layer.ljust(5)) # type: ignore
    AttributeError: 'NoneType' object has no attribute 'set_postfix_str'

---

**Comment by ghost** [comment]
Notation seem working else thank that a good mod to understand... It's nice work :)
